# Generated by Django 5.1.5 on 2025-01-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address',
        ),
    ]
